import Head from "next/head";
import Layout from "../components/layout";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Sample - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.container}>
          <div className={styles.title}>
            {["Welcome", "to", "Pokemon Family"].map((str: string, idx: number) => (
              <span key={idx}>{str}</span>
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
}
